### ISSUE TITLE
OAUTH 

### ISSUE THREAD

**Issue by josuebrunel** [josuebrunel/myql#12]
Implements a method allowing  LokingYQL to access data requiring authentification.

**Comment by josuebrunel** [comment]
https://developer.yahoo.com/forum/OAuth-General-Discussion-YDN-SDKs/OAuth-two-legged-documentation-omission-/1253773254000-104aac85-a511-3985-87b8-36f430730ca4/

**Comment by josuebrunel** [comment]
Now is the time to close this issue but above all make oauth work properly [Yahoo Oauth2 Guide](https://developer.yahoo.com/oauth2/guide/)

**Comment by josuebrunel** [comment]
To refresh the token, check [this](https://developer.yahoo.com/oauth/guide/oauth-refreshaccesstoken.html).
***oauth_session_handle*** is the key here

**Comment by josuebrunel** [comment]
Hi @almartin82, thanks a lot for your help :smile: . I managed to make OAuth works, and i have an idea on how to refresh the token, Will keep you posted about the implementation.

**Comment by almartin82** [comment]
:+1: :+1: :+1: !

**Comment by josuebrunel** [comment]
https://nullinfo.wordpress.com/oauth-yahoo/
